"use client";

import { useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { Activity, Camera, Check, Crosshair, Focus, Layers3, Maximize2, MousePointer2, ScanLine, ShieldCheck, Sparkles, Target } from "lucide-react";
import { SimulationTopbar } from "@/components/simulation/SimulationTopbar";
import { PatientPanel } from "@/components/simulation/PatientPanel";
import { ProcedurePanel } from "@/components/simulation/ProcedurePanel";
import { ToolBar } from "@/components/simulation/ToolBar";
import { HospitalScene } from "@/components/simulation/HospitalScene";
import { WebcamPractice } from "@/components/simulation/WebcamPractice";
import { useSimulation } from "@/components/simulation/SimulationProvider";
import type { CameraMode } from "@/types/simulation";
import "./simulation.css";

const regionActions: Record<string,string[]>={"Right arm":["Inspect wound","Check circulation","Prepare sterile field","Begin suturing"],Head:["Inspect","Check pupils","Assess orientation"],Chest:["Observe breathing","Auscultate","Check monitor"],Abdomen:["Inspect","Palpate","Assess discomfort"],"Left arm":["Inspect","Check pulse","Check movement"],"Left leg":["Inspect","Check circulation","Check movement"],"Right leg":["Inspect","Check circulation","Check movement"]};

export default function SimulationPage(){const {state,setCameraMode,selectRegion}=useSimulation();return <div className="simulation-page"><SimulationTopbar/><div className="simulation-body"><PatientPanel/><section className="simulation-center"><div className="simulation-viewport">{state.cameraMode==="webcam"?<WebcamPractice/>:<HospitalScene/>}<div className="viewport-top-left"><span><i/>3D virtual patient</span><strong>{state.anatomyOverlay?"Anatomy inspection":"Clinical room · Bed 04"}</strong></div><div className="view-preset-dock">{[["room",Camera,"Room overview"],["patient",Focus,"Patient view"],["closeup",Maximize2,"Right forearm"],["tray",ScanLine,"Instrument tray"],["anatomy",Layers3,"Anatomy inspection"]].map(([mode,Icon,label])=>{const I=Icon as typeof Camera;return <button key={mode as string} className={state.cameraMode===mode?"active":""} onClick={()=>setCameraMode(mode as CameraMode)} title={label as string}><I size={14}/><span>{label as string}</span></button>})}</div>{state.selectedRegion&&state.cameraMode!=="webcam"&&<div className="selected-region-card"><span>Selected region</span><div><i><Crosshair size={15}/></i><strong>{state.selectedRegion}</strong><b>{state.selectedRegion==="Right arm"?"Injury site":"Assessment region"}</b></div><p>Available actions</p><div className="region-action-chips">{(regionActions[state.selectedRegion]??["Inspect"]).map(action=><button key={action} onClick={()=>state.selectedRegion!=="Right arm"&&selectRegion("Right arm")}>{action}</button>)}</div></div>}{state.selectedRegion==="Right arm"&&state.cameraMode!=="webcam"&&<SutureInteraction/>}<div className="viewport-bottom-status"><span><MousePointer2 size={12}/>Drag to orbit</span><span><ScanLine size={12}/>Scroll to zoom</span><span className={state.anatomyOverlay?"on":""}><Layers3 size={12}/>Anatomy {state.anatomyOverlay?"on":"off"}</span><b>Educational simulation · No real-patient use</b></div></div><ToolBar/></section><ProcedurePanel/></div>{state.paused&&<div className="paused-overlay"><div><Activity size={24}/><strong>Simulation paused</strong><p>The timer and guided scenario are paused.</p></div></div>}</div>}

function SutureInteraction(){const {state,performAction}=useSimulation();const [position,setPosition]=useState(22);const [angle,setAngle]=useState(68);const [dragging,setDragging]=useState(false);const track=useRef<HTMLDivElement>(null);const onMove=(event:ReactPointerEvent<HTMLDivElement>)=>{if(!dragging||!track.current)return;const rect=track.current.getBoundingClientRect();setPosition(Math.max(4,Math.min(96,(event.clientX-rect.left)/rect.width*100)))};const inPosition=position>=43&&position<=57;const goodAngle=angle>=45&&angle<=60;const nextAction=state.stitchPhase===0?"Position instrument":state.stitchPhase===1?"Match angle":state.stitchPhase===2?"Begin stitch":state.stitchPhase===3?"Pull suture":state.stitchPhase===4?"Tie knot":state.stitchPhase===5?"Cut suture":"Finish procedure";const ready=state.stitchPhase===0?inPosition:state.stitchPhase===1?goodAngle:true;return <div className="suture-interaction"><div className="suture-hud-head"><div><Sparkles size={13}/><span>Guided closure</span></div><b>Phase {Math.min(state.stitchPhase+1,7)} / 7</b></div><div className="position-track" ref={track} onPointerMove={onMove} onPointerUp={()=>setDragging(false)} onPointerLeave={()=>setDragging(false)}><span className="position-entry"><Target size={12}/></span><i className={inPosition?"ideal-position active":"ideal-position"}/><button style={{left:`${position}%`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDragging(true)}} aria-label="Drag needle holder to entry point"><MousePointer2 size={14}/></button></div><div className="angle-control"><div><span>Recommended angle</span><strong>45°–60°</strong></div><div><span>Current angle</span><strong className={goodAngle?"good":"warning"}>{angle}°</strong></div><input aria-label="Instrument angle" type="range" min="30" max="85" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></div><div className="suture-readiness"><span className={inPosition?"complete":""}>{inPosition?<Check size={11}/>:<Crosshair size={11}/>}Entry aligned</span><span className={goodAngle?"complete":""}>{goodAngle?<Check size={11}/>:<ScanLine size={11}/>}Angle matched</span><span className={state.stitchPhase>=3?"complete":""}>{state.stitchPhase>=3?<Check size={11}/>:<ShieldCheck size={11}/>}Guided arc</span></div><button className="advance-stitch" disabled={!ready||!state.selectedTool} onClick={()=>performAction(nextAction)}>{state.selectedTool?nextAction:"Select needle holder first"}</button></div>}
