"use client";

import { Activity, Award, CalendarDays, Clock3, Flame, Medal, ShieldCheck, Sparkles, Target, TrendingUp, Trophy } from "lucide-react";
import { Area, AreaChart, Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { DashboardHeader } from "@/components/layout/DashboardHeader";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { trendData } from "@/data/mockData";
import "./progress.css";

const skills = [{name:"Tool Control",level:5,value:82,color:"cyan"},{name:"Suturing Accuracy",level:4,value:74,color:"blue"},{name:"Bimanual Coordination",level:3,value:61,color:"amber"},{name:"Safety Awareness",level:6,value:94,color:"green"}];
const badges = [[Trophy,"First Session","Completed your first guided exercise",true],[Target,"Precision Starter","Reached 80% accuracy",true],[Activity,"Stable Hands","Held stability above 80%",true],[ShieldCheck,"Safety First","Three sessions with no high alerts",true],[Flame,"Suturing Streak","Practise suturing 5 days in a row",false],[Medal,"Motion Master","Reach 90% motion efficiency",false]] as const;
const activity = [0,1,2,0,3,1,0, 1,2,1,3,4,2,0, 0,1,3,2,2,4,1, 2,3,4,2,1,3,0, 1,2,3,4,3,2,1, 0,1,2,3,4,2,0, 2,3,2,1,3,4,1, 1,2,3,2,4,3,0];

export default function ProgressPage(){
 return <div className="page-wrap progress-page"><DashboardHeader title="Progress & insights" description="Eight weeks of deliberate practice, measured across skills, time, and consistency." />
  <section className="progress-summary-grid"><Card><span className="progress-summary-icon cyan"><TrendingUp size={17}/></span><div><small>Overall score</small><strong>82<em>/100</em></strong><span className="positive">+14% this month</span></div></Card><Card><span className="progress-summary-icon blue"><Clock3 size={17}/></span><div><small>Practice time</small><strong>7.8<em> hrs</em></strong><span>94 min this week</span></div></Card><Card><span className="progress-summary-icon amber"><Flame size={17}/></span><div><small>Current streak</small><strong>7<em> days</em></strong><span>Personal best: 11 days</span></div></Card><Card><span className="progress-summary-icon green"><Award size={17}/></span><div><small>Personal best</small><strong>86<em>/100</em></strong><span>Needle Positioning</span></div></Card></section>
  <section className="progress-chart-grid"><Card className="score-trend-card"><div className="progress-card-title"><div><p className="eyebrow">Performance trend</p><h2>Score over time</h2></div><Badge tone="green">+18 points</Badge></div><div className="score-trend-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trendData}><defs><linearGradient id="scoreFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#29c7d8" stopOpacity={.3}/><stop offset="1" stopColor="#29c7d8" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.08)" vertical={false}/><XAxis dataKey="week" tick={{fill:"#64788e",fontSize:9}} axisLine={false} tickLine={false}/><YAxis domain={[50,100]} tick={{fill:"#64788e",fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#0e1b2b",border:"1px solid rgba(148,163,184,.2)",borderRadius:9,fontSize:10}}/><Area type="monotone" dataKey="score" stroke="#48d7e3" strokeWidth={2.5} fill="url(#scoreFill)"/></AreaChart></ResponsiveContainer></div></Card><Card className="practice-time-card"><div className="progress-card-title"><div><p className="eyebrow">Weekly effort</p><h2>Practice minutes</h2></div></div><div className="practice-time-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={trendData}><CartesianGrid stroke="rgba(148,163,184,.07)" vertical={false}/><XAxis dataKey="week" tick={{fill:"#64788e",fontSize:8}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"#64788e",fontSize:8}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#0e1b2b",border:"1px solid rgba(148,163,184,.2)",borderRadius:9,fontSize:10}}/><Bar dataKey="minutes" fill="#254f7c" radius={[3,3,0,0]}/><Line dataKey="minutes" stroke="#57dce7" strokeWidth={1.5} dot={false}/></ComposedChart></ResponsiveContainer></div></Card></section>
  <section className="progress-middle-grid"><Card className="activity-card"><div className="progress-card-title"><div><p className="eyebrow">Consistency</p><h2>Practice activity</h2></div><span><CalendarDays size={13}/>Last 8 weeks</span></div><div className="heatmap-wrap"><div className="heatmap-labels"><span>Mon</span><span>Wed</span><span>Fri</span><span>Sun</span></div><div className="activity-heatmap">{activity.map((value,i)=><i key={i} className={`level-${value}`} title={`${value*12} practice minutes`}/>)}</div></div><div className="heatmap-legend"><span>Less</span>{[0,1,2,3,4].map(v=><i className={`level-${v}`} key={v}/>)}<span>More</span></div></Card><Card className="completion-card"><div className="progress-card-title"><div><p className="eyebrow">Course coverage</p><h2>Scenario completion</h2></div><strong>64%</strong></div>{[["Incision Path Tracing",100],["Peg Transfer",83],["Needle Positioning",58],["Simple Interrupted Suture",71]].map(([name,value])=><div className="completion-row" key={name as string}><div><span>{name}</span><strong>{value}%</strong></div><i><b style={{width:`${value}%`}}/></i></div>)}</Card></section>
  <section className="skills-section"><div className="progress-section-head"><div><p className="eyebrow">Capabilities</p><h2>Skill progression</h2></div><span>Levels reflect simulated practice data</span></div><div className="skill-progression-grid">{skills.map(skill=><Card className="skill-progress-card" key={skill.name}><div><span className={`skill-level-icon ${skill.color}`}>L{skill.level}</span><div><strong>{skill.name}</strong><small>Level {skill.level} · {skill.value >= 80 ? "Advanced" : skill.value >= 70 ? "Developing" : "Foundational"}</small></div></div><div className="skill-progress-line"><i><b className={skill.color} style={{width:`${skill.value}%`}}/></i><span>{skill.value}%</span></div><p>{skill.value >= 85 ? "Excellent consistency across recent attempts." : skill.value >= 75 ? "On track—focus on controlled repetition." : "Recommended: two focused drills this week."}</p></Card>)}</div></section>
  <section className="achievement-section"><div className="progress-section-head"><div><p className="eyebrow"><Sparkles size={12}/> Milestones</p><h2>Achievements</h2></div><span>4 of 6 unlocked</span></div><div className="achievement-grid">{badges.map(([Icon,title,text,earned])=><Card className={earned?"achievement-card earned":"achievement-card locked"} key={title}><span><Icon size={21}/></span><div><strong>{title}</strong><p>{text}</p>{earned?<Badge tone="green">Unlocked</Badge>:<Badge tone="slate">In progress</Badge>}</div></Card>)}</div></section>
 </div>;
}
